move build configuration into `pyproject.toml`
spacetelescope/stistools pull request #145
Opened 2022-09-15 18:06 UTC by zacharyburnett

`setuptools` now supports the `[project]` table, which is defined by [PEP621](https://peps.python.org/pep-0621).

Additionally, `setuptools` now supports its own entry in `pyproject.toml` called `[tool.setuptools]` (https://github.com/pypa/setuptools/issues/1688, https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#setuptools-specific-configuration); however, it comes with the following disclaimer:
> Support for declaring configurations not standardized by [PEP 621](https://peps.python.org/pep-0621/) (i.e. the `[tool.setuptools]` table), is still in **beta** stage and might change in future releases.

It is likely that this functionality with `setuptools` will leave beta stage upon the release of Python 3.11, with its native implementation of `tomli`

Given this, we can attempt to consolidate the build configuration into a single `pyproject.toml` file that can possibly be read by other build systems in the future.

2023-02-17 12:26 UTC, nden requested changes

2023-02-17 12:26 UTC, nden commented on pyproject.toml
> +    "astropy>=4.1",
```suggestion
    "astropy>=5.1",
```

2023-02-17 12:26 UTC, nden commented on pyproject.toml
> +    "relic",
It'd be good to stop using relic in stistools. It is an old in-house build system managing releases

2023-02-23 21:09 UTC, zacharyburnett commented
removing reliance on `relic` would also likely solve this issue: https://github.com/spacetelescope/stenv/issues/78

2023-02-25 15:12 UTC, nden approved these changes

2023-02-25 16:34 UTC, merged

2023-02-28 19:53 UTC, sean-lockwood commented
@zacharyburnett -
The RTD site was rebuilt around the time this PR was merged.  It looks like the docs built without `autodoc`, as most of the function descriptions are now blank.

E.g.:
https://stistools.readthedocs.io/en/latest/inttag.html

<img width="900" alt="image" src="https://user-images.githubusercontent.com/5471441/221963742-4a98212b-c1df-4d0d-ab8d-88a1cc6e2adb.png">

2023-02-28 21:03 UTC, zacharyburnett commented
> The RTD site was rebuilt around the time this PR was merged. It looks like the docs built without autodoc, as most of the function descriptions are now blank.

That is strange; they populate on HTML built locally on my machine. I will look into this issue.